version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80/tcp"
#      - "443:443/tcp"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
  web:
    image: testing:latest
    container_name: web
    command: gunicorn binder_test.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/usr/src/app/staticfiles
      - ./media:/usr/src/app/media
    expose:
      - "8000"
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
